name: cicd

on:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mitin20/prueba-gha:latest

      - name: test connection to cluster
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: get pods

      - name: deploy to cluster
        uses: yokawasa/action-setup-kube-tools@v0.4.0
        with:
        kubectl: "1.20.2"
        kustomize: "3.7.0"

      - name: kubectl
        id: kubectl
        run: |
          mkdir -p ~/.kube/
          echo $KUBE_CONFIG_DATA | base64 -d > ~/.kube/config
          cd .kustomize
          kustomize build . | kubectl apply -f -
