on: push
name: deploy
jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build and push to docker
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_REPOSITORY}}
          #repository: ${{ github.repository }}
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}
  deploy-to-cluster:
    name: deploy to cluster
    runs-on: ubuntu-latest
    env:
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      HOLA: test
    #needs: build-and-push
    steps:
      - uses: actions/checkout@master
      - name: deploy to cluster
        uses: yokawasa/action-setup-kube-tools@v0.4.0
        with:
          kubectl: "1.20.2"
          kustomize: "3.7.0"
      - name: kubectl
        id: kubectl
        run: |
          mkdir -p ~/.kube/
          echo $KUBE_CONFIG_DATA | base64 -d > ~/.kube/config
          cd .kustomize
          kustomize build . | kubectl apply -f -
